# overrides from helm/values-prod.yaml.
# all the properties defined here will take precedence against values-prod.yaml file
microservice-chart:
  namespace: "pay-wallet"
  image:
    repository: pagopapitncoreacr.azurecr.io/pagopajwtissuerservice
  ingress:
    create: true
    host: "itnprod.pay-wallet.internal.platform.pagopa.it"
    path: /pagopa-jwt-issuer-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "pay-wallet-workload-identity"
  envConfig:
    OTEL_SERVICE_NAME: "pagopa-pay-wallet-jwt-issuer-service"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.otel.svc:4317"
    AZURE_KV_ENDPOINT: "https://pagopa-p-pay-wallet-kv.vault.azure.net/"
    SECRET_KEY_NAME: "jwt-token-issuer-cert"
    SECRET_KEY_PASSWORD: ""
    JWT_ISSUER: "pagopa-pay-wallet-jwt-issuer-service"
  keyvault:
    name: "pagopa-p-pay-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tolerations:
    - effect: "NoSchedule"
      key: "paymentWalletOnly"
      operator: "Equal"
      value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - paywallet
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: pagopajwtissuerservice
          namespaces: [ "pay-wallet" ]
          topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: "48a74dad-26f3-4916-ba45-ddda27d950b1"