# overrides from helm/values-dev.yaml.
# all the properties defined here will take precedence against values-dev.yaml file
microservice-chart:
  namespace: "ecommerce"
  image:
    repository: pagopadcommonacr.azurecr.io/pagopajwtissuerservice
  ingress:
    create: true
    host: "weudev.ecommerce.internal.dev.platform.pagopa.it"
    path: /pagopa-jwt-issuer-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "ecommerce-workload-identity"
  envConfig:
    OTEL_SERVICE_NAME: "pagopa-ecommerce-jwt-issuer-service"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    AZURE_KV_ENDPOINT: "https://pagopa-d-ecommerce-kv.vault.azure.net/"
    SECRET_KEY_NAME: "jwt-token-issuer-cert-ec"
    SECRET_KEY_PASSWORD: ""
    JWT_ISSUER: "ecom-jwt-issuer-service"
    WELL_KNOWN_OPENID_CONFIGURATION_BASE_PATH: "https://weudev.ecommerce.internal.dev.platform.pagopa.it/pagopa-jwt-issuer-service"
  keyvault:
    name: "pagopa-d-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  azure:
    workloadIdentityClientId: "1be61b58-24e2-49c8-b401-89ebd004bf2e"

