parameters:
  # Required
  - name: "ENV_FILE"
    type: string
  - name: "API_TEST_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string
  - name: "USE_NEWMAN_DOCKER_IMAGE"
    type: boolean


steps:
  - ${{ if eq(parameters['USE_NEWMAN_DOCKER_IMAGE'], False) }}:
      - script: |
          npm install -g newman
        displayName: 'Newman installation'
      - script: |
          newman run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }}  --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
        displayName: 'Run api test'
  - ${{ else }}:
      - script: |
          ls
          docker run -v .:/etc/newman -t postman/newman run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }}  --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
        displayName: 'Run api test'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'