parameters:
  # Required
  - name: "ENV_FILE"
    type: string
  - name: "API_TEST_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string
  - name: "USE_NEWMAN_DOCKER_IMAGE"
    type: boolean
  - name: "SERVICE_API_KEY"
    type: string


steps:
  - checkout: self
    displayName: "Checkout repo"
    #clean: false
  - script: |
      NEWMAN_TEST_RUN="run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }} --env-var API-KEY=${{ parameters.SERVICE_API_KEY }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml"
      echo "Newman run command: [$NEWMAN_TEST_RUN]"
    displayName: 'Set Newman run command'
  - ${{ if eq(parameters['USE_NEWMAN_DOCKER_IMAGE'], False) }}:
      - script: |
          yarn global add newman
        displayName: 'Newman installation'
      - script: |
          newman $(echo $NEWMAN_TEST_RUN)
        displayName: 'Run api test'
  - ${{ else }}:
      - script: |
          docker run -v .:/etc/newman -t postman/newman $(echo $NEWMAN_TEST_RUN)
        displayName: 'Run api test'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'