microservice-chart:
  namespace: ""
  nameOverride: ""
  fullnameOverride: "pagopa-jwt-issuer-service"
  image:
    repository: ""
    tag: "0.6.1"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 3
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: false
  serviceAccount:
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 60
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  envConfig:
    ROOT_LOGGING_LEVEL: "info"
    OTEL_RESOURCE_ATTRIBUTES_DEPLOYMENT_ENVIRONMENT: "prod"
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    KEYSTORE_CACHE_MAXSIZE: "10"
    KEYSTORE_CACHE_TTL_MINS: "1"
    AZURE_MAX_RETRY: "3"
    AZURE_RETRY_DELAY_MILLIS: "500"
    SECURITY_API_KEY_SECURED_PATHS: "/tokens"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  secretProviderClass:
    create: true
